/**
 * FocusPointCard.tsx
 * ──────────────────
 * ╔══════════════════════════════════════════╗
 * ║  🎯  FOCUS POINT          [Subtle]  [✕] ║
 * ╠══════════════════════════════════════════╣
 * ║  "There's a key idea hiding in this     ║
 * ║   paragraph. Can you spot the author's  ║
 * ║   main argument before moving on?"      ║
 * ║                                         ║
 * ║  ┌──────────────────────────────────┐   ║
 * ║  │     I've thought about it  →     │   ║
 * ║  └──────────────────────────────────┘   ║
 * ╚══════════════════════════════════════════╝
 *
 * A curiosity-spark prompt generated by the LLM based on the current text
 * window.  No interaction beyond acknowledgement — the user thinks about the
 * prompt while reading, then dismisses it.
 *
 * To edit the visual appearance of Focus Point cards, change this file only.
 */

import type { CSSProperties } from "react";
import type {
  ActiveIntervention,
  FocusPointContent,
} from "../../services/interventionService";
import { InterventionCardShell } from "./InterventionCardShell";

interface FocusPointCardProps {
  intervention: ActiveIntervention;
  onDismiss:    (id: number) => void;
}

export function FocusPointCard({ intervention, onDismiss }: FocusPointCardProps) {
  const content = intervention.content as FocusPointContent | null;
  const prompt  = content?.prompt ?? "What is the core idea in the passage you just read?";

  const promptText: CSSProperties = {
    fontSize:   "14px",
    lineHeight: 1.65,
    color:      "var(--text, #111827)",
    margin:     "0 0 14px",
    fontStyle:  "italic",
  };

  const dismissBtn: CSSProperties = {
    width:          "100%",
    padding:        "9px 14px",
    background:     "rgba(79,110,247,0.09)",
    border:         "1.5px solid rgba(79,110,247,0.25)",
    borderRadius:   "8px",
    color:          "#4f6ef7",
    fontSize:       "13px",
    fontWeight:     600,
    cursor:         "pointer",
    display:        "flex",
    alignItems:     "center",
    justifyContent: "center",
    gap:            "6px",
    transition:     "background 0.15s",
  };

  return (
    <InterventionCardShell
      tier={intervention.tier}
      icon="🎯"
      title="Focus Point"
      onDismiss={() => onDismiss(intervention.intervention_id!)}
    >
      <p style={promptText}>"{prompt}"</p>
      <button
        type="button"
        style={dismissBtn}
        onClick={() => onDismiss(intervention.intervention_id!)}
      >
        I've thought about it →
      </button>
    </InterventionCardShell>
  );
}
